### ISSUE TITLE
post date and text 

### ISSUE THREAD

**Issue by raggabrashtrout** [Hashirama/OFDL#19]
More of a request than a issue
Is it possible to save the post date and text some where and link it to the downloaded files?
Maybe in the database
or
save the JSON
Thanx

**Comment by Hashirama** [comment]
The date of the post and the caption?

Like add it to the file properties or something?

Or a json file that has the same name as the file and holds the caption and date?

**Comment by ThailandTony** [comment]
Basically the issue is after down loading a users content your left with tens or even hundreds of files with seemingly random names with no way of putting them in order or context
Some content generators upload sets of pictures or  videos over multiple posts

OF have changed the setup so you can no longer save the entire OF page and find the Down Loaded file or postId in the HTML
BTW
You can't always put the entire post text in the file name, because 
1. it's sometimes  to long, 
2. can contain characters that don't belong in a file name
3. lastly there may not be text


Putting a date +\n\n jpg or mp4 in the file and saving the post text some place would help for example in the database
something like
YYYYMMDD_postId\n\n\n.jpg

I get for most people this isn't important

My PY isn't good enough but I think your fetching JSON from the OF server?
If so I'd assume each post object would have postId postDate image / video url(s) and post text these could easily be saved in the database  

Hope this makes sense
Thanx for your consideration

**Comment by Hashirama** [comment]
Yeah it uses their API which returns JSON.

So posts saved by their date and inside the database the caption/text along with the post id?

**Comment by ThailandTony** [comment]
Yes but I think you need the postId in the file name as well 
otherwise  if you just save by date there's no way of linking the file back to the database entry

If I knew python, I'd save each file something like this
Date_postId_Count.Extension

so if a user post 10 pictures today on 1 post each picture would be uniquely named
20210125_12345_001.jpg
20210125_12345_002.jpg
...
20210125_12345_010.jpg

Alternatively keep everything as is and just save the JSON from the API somewhere 

There are many ways of doing this the key is to be able link the saved file back to the post text then the end user can do what they like 

Hope that makes sense

Thank you

**Comment by Hashirama** [comment]
Yeah it makes sense. I'll work on it.

**Comment by ThailandTony** [comment]
Hi
I was wondering if there was any progress on this?

Thanx
