### ISSUE TITLE
Videos and pictures cannot be downloaded correctly.

### ISSUE THREAD

**Issue by gcodexman** [Hashirama/OFDL#26]
Suppose an account has 500 pictures and 800 videos. 

But only grabbed 210 pictures and 430 videos downloaded. 

Much is missing.

**Comment by soulburn74** [comment]
I just trying this out for the first time today, having this same issue.

**Comment by Hashirama** [comment]
> I just trying this out for the first time today, having this same issue.

Some images and videos are hidden behind a paywall as they haven't been paid for. 

I believe this explains the difference in what's displayed and what's downloaded.

**Comment by soulburn74** [comment]
I wish that was true. I've been playing with a few different OF scrapers, as the DC version has been completely broken since OF implemented IP banning......and they haven't gotten a new version completely working yet, but between your script and tux1c's There is a big difference in number of files being downloaded. only problem with Tux's is that that person's script doesn't download paid content very well. I REALLY like the fact that your script has a gui.......... I just wish it didn't skip things (like for a content provider that has 1000's of vids and many 1000's of pictures, I can verify there are no hidden pay wall choices on this sub, and can also verify there isn't 1000's of duplicates.......If you'd like to compare notes or have me show you anything specific that might help lead the way, I'd gladly do so.

**Comment by Hashirama** [comment]
Yah, my email is on my profile.
